version: "3.8"

services:

  aria2c:
    container_name: aria2c
    image: p3terx/aria2-pro
    environment:
      - PUID=33
      - PGID=33
      - UMASK_SET=022
      - RPC_SECRET=qiuqiu123
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=America/New_York
    volumes:
      - ${PWD}/aria2-config:/config
      - /mnt/data/owncloud/files/files/sjq/files/download:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
    network_mode: host
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=aria2.thesjq.com
      - LETSENCRYPT_HOST=aria2.thesjq.com
      - LETSENCRYPT_EMAIL=ivy22233qiu@live.com
    expose:
      - 6880
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - nginx_reverse_proxy_proxy-tier
networks:
  nginx_reverse_proxy_proxy-tier:
    external: true
