version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    # networks:
    #   - nginx_reverse_proxy_proxy-tier
    environment:
      - PUID=33
      - PGID=33
      - VERSION=docker
      - PLEX_CLAIM=claim-QDjerR7r48xASzmSYTLN
    expose:
      - 32400
      - 33400
    volumes:

      - /mnt/data/owncloud/files/files/sjq/files/config:/config
      - /mnt/data/owncloud/files/files/sjq/files/tv:/tv
      - /mnt/data/owncloud/files/files/sjq/files/movie:/movies
      - /mnt/data/owncloud/files/files/sjq/files/zgg:/porn
      - /mnt/data/owncloud/files/files/sjq/files/public:/public
      - /mnt/data/owncloud/files/files/sjq/files/backup:/backup
      - /mnt/data/owncloud/files/files/sjq/files/:/allfiles

    restart: unless-stopped
networks:
  nginx_reverse_proxy_proxy-tier:
    external: true