version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: 33:33
    expose:
      - 8080
    volumes:
      - /mnt/data/owncloud/files/files/sjq/files:/data
      - ${PWD}/CONFIG_DIR:/config
    environment:
      - VIRTUAL_PORT=8080
      - FB_BASEURL=/filebrowser
      - VIRTUAL_HOST=www.thesjq.com
      - LETSENCRYPT_HOST=www.thesjq.com
      - LETSENCRYPT_EMAIL=ivy22233qiu@live.com
    restart: always
    networks:
      - nginx_reverse_proxy_proxy-tier
networks:
  nginx_reverse_proxy_proxy-tier:
    external: true
