version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qiuqiu123
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/data/nextcloud_data_docker_compose:/var/nextclouddata
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/var/nextclouddata
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=file.thesjq.com
      - LETSENCRYPT_HOST=file.thesjq.com
      - LETSENCRYPT_EMAIL=ivy22233qiu@live.com
    depends_on:
      - app
    networks:
      - nginx_reverse_proxy_proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis



volumes:
  db:
  nextcloud:

networks:
  nginx_reverse_proxy_proxy-tier:
    external: true
